'use strict';
const form=document.querySelector('#search'),status=document.querySelector('#status'),results=document.querySelector('#results'),weather=document.querySelector('#weather'),submit=document.querySelector('#submit');
let controller;
function description(code){if(code===0)return 'Clear sky';if(code<=3)return 'Partly cloudy';if([45,48].includes(code))return 'Fog';if(code>=51&&code<=57)return 'Drizzle';if(code>=61&&code<=67)return 'Rain';if(code>=71&&code<=77)return 'Snow';if(code>=80&&code<=82)return 'Rain showers';if([85,86].includes(code))return 'Snow showers';if(code>=95)return 'Thunderstorms';return 'Conditions unavailable';}
function element(tag,text,className){const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node;}
async function json(url,signal){const response=await fetch(url,{signal});if(!response.ok)throw new Error('Weather service is unavailable. Please try again.');return response.json();}
async function load(place){
controller?.abort();controller=new AbortController();const signal=controller.signal;
status.textContent='Loading forecast…';weather.replaceChildren();results.replaceChildren();
try{const query=new URLSearchParams({latitude:place.latitude,longitude:place.longitude,current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m',daily:'weather_code,temperature_2m_max,temperature_2m_min',timezone:'auto',forecast_days:'5'});
const data=await json('https://api.open-meteo.com/v1/forecast?'+query,signal);if(!data.current||!data.daily)throw new Error('No forecast is available for this location.');
weather.append(element('h2',[place.name,place.admin1,place.country].filter(Boolean).join(', ')),element('div',Math.round(data.current.temperature_2m)+'°','temperature'),element('p',description(data.current.weather_code)),element('p','Feels like '+Math.round(data.current.apparent_temperature)+'° • Humidity '+data.current.relative_humidity_2m+'% • Wind '+data.current.wind_speed_10m+' km/h'));
const days=element('div','','forecast');data.daily.time.forEach((date,i)=>{const day=element('div','','day');day.append(element('strong',new Date(date+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})),element('p',description(data.daily.weather_code[i])),element('small',Math.round(data.daily.temperature_2m_max[i])+'° / '+Math.round(data.daily.temperature_2m_min[i])+'°'));days.append(day);});weather.append(element('h3','Five-day forecast'),days);status.textContent='Updated '+data.current.time.replace('T',' ')+' ('+data.timezone+').';
}catch(error){if(error.name!=='AbortError')status.textContent=error.message||'Could not load weather. Check your connection.';}}
form.addEventListener('submit',async event=>{event.preventDefault();controller?.abort();controller=new AbortController();const signal=controller.signal;submit.disabled=true;results.replaceChildren();weather.replaceChildren();status.textContent='Finding cities…';
try{const query=new URLSearchParams({name:document.querySelector('#city').value.trim(),count:'5',language:'en',format:'json'});const data=await json('https://geocoding-api.open-meteo.com/v1/search?'+query,signal);if(!data.results?.length){status.textContent='No cities found. Try another spelling.';return;}status.textContent='Choose your city:';for(const place of data.results){const button=element('button',[place.name,place.admin1,place.country].filter(Boolean).join(', '));button.type='button';button.addEventListener('click',()=>load(place));results.append(button);}}
catch(error){if(error.name!=='AbortError')status.textContent=error.message||'Could not search. Check your connection.';}finally{if(controller.signal===signal)submit.disabled=false;}});
